version: '3'
services:
  golang:
    build: .
    ports:
      - 80:8080
    volumes:
      - .:/go/src/app/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -dbPath ./data -sharedDb
